/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class viin_patch_update_PatchUpdate */

#ifndef _Included_viin_patch_update_PatchUpdate
#define _Included_viin_patch_update_PatchUpdate
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     viin_patch_update_PatchUpdate
 * Method:    patch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_cundong_utils_PatchUtils_patch
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
