/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cundong_utils_JPatch */

#ifndef _Included_com_cundong_utils_JPatch
#define _Included_com_cundong_utils_JPatch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cundong_utils_PatchUtils
 * Method:    genNewApk
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_cundong_utils_PatchUtils_patch
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
